### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by redzonej** [graywolf336/RocketChatApps#14]
Trying to figure out how to actually deploy one of these apps inside docker container deployment server running. Can't seem to find much documentation on anything other than marketplace installs. Is it possible?

**Comment by frdmn** [comment]
Have you enabled the Apps dev mode? (Admin UI → General → Apps → Enable development mode)

Once done you should be able to upload apps in the "Apps" section.

**Comment by redzonej** [comment]
> Have you enabled the Apps dev mode? (Admin UI → General → Apps → Enable development mode)
> 
> Once done you should be able to upload apps in the "Apps" section.

Yes that is enabled. I think the issue I'm running into is doing rc-apps package. It seems to fail on rc-apps package OR rc-apps create with error:
    SyntaxError: Invalid regular expression:
    /(?:\[(?<code>\d+)m|\]8;;(?<uri>.*))/: Invalid group
/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

Are you able to build it to an uploadable zip file on your end?

**Comment by redzonej** [comment]
Resolved by all the improvements on recent builds.
